/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../a2t-shared/a2t-headline/a2t-headline.component.ngfactory';
import * as i2 from '../a2t-shared/a2t-headline/a2t-headline.component';
import * as i3 from '../a2t-shared/a2t-error/a2t-error.component.ngfactory';
import * as i4 from '../a2t-shared/a2t-error/a2t-error.component';
import * as i5 from '../a2t-shared/a2t-form/a2t-form.component.ngfactory';
import * as i6 from '../a2t-shared/a2t-form/a2t-form.component';
import * as i7 from '../a2t-shared/a2t-form/a2t-form.service';
import * as i8 from '../a2t-shared/a2t-links/a2t-links.component.ngfactory';
import * as i9 from '../a2t-shared/a2t-links/a2t-links.component';
import * as i10 from './a2t-sign-in.component';
import * as i11 from '../../angular2-token.service';
import * as i12 from '@angular/router';
const styles_A2tSignInComponent:any[] = ([] as any[]);
export const RenderType_A2tSignInComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_A2tSignInComponent,data:{}});
export function View_A2tSignInComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),2,'a2t-headline',([] as any[]),(null as any),(null as any),
      (null as any),i1.View_A2tHeadlineComponent_0,i1.RenderType_A2tHeadlineComponent)),
      i0.ɵdid(49152,(null as any),0,i2.A2tHeadlineComponent,([] as any[]),(null as any),
          (null as any)),(_l()(),i0.ɵted(0,['Sign In'])),(_l()(),i0.ɵted((null as any),
          ['\n        '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'a2t-error',
          ([] as any[]),(null as any),(null as any),(null as any),i3.View_A2tErrorComponent_0,
          i3.RenderType_A2tErrorComponent)),i0.ɵdid(49152,(null as any),0,i4.A2tErrorComponent,
          ([] as any[]),{errors:[0,'errors']},(null as any)),(_l()(),i0.ɵted((null as any),
          ['\n        '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'a2t-form',
          ([] as any[]),(null as any),(null as any),(null as any),i5.View_A2tFormComponent_0,
          i5.RenderType_A2tFormComponent)),i0.ɵdid(49152,(null as any),0,i6.A2tFormComponent,
          [i7.A2tFormService],(null as any),(null as any)),(_l()(),i0.ɵted(0,['Sign In'])),
      (_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),1,'a2t-links',[['case','sign-in']],(null as any),(null as any),
          (null as any),i8.View_A2tLinksComponent_0,i8.RenderType_A2tLinksComponent)),
      i0.ɵdid(49152,(null as any),0,i9.A2tLinksComponent,([] as any[]),{case:[0,'case']},
          (null as any)),(_l()(),i0.ɵted((null as any),['\n    ']))],(_ck,_v) => {
    var _co:i10.A2tSignInComponent = _v.component;
    const currVal_0:any = _co._errors;
    _ck(_v,6,0,currVal_0);
    const currVal_1:any = 'sign-in';
    _ck(_v,13,0,currVal_1);
  },(null as any));
}
export function View_A2tSignInComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'a2t-sign-in',
      ([] as any[]),(null as any),(null as any),(null as any),View_A2tSignInComponent_0,
      RenderType_A2tSignInComponent)),i0.ɵprd(512,(null as any),i7.A2tFormService,
      i7.A2tFormService,([] as any[])),i0.ɵdid(49152,(null as any),0,i10.A2tSignInComponent,
      [i7.A2tFormService,i11.Angular2TokenService,i12.Router],(null as any),(null as any))],
      (null as any),(null as any));
}
export const A2tSignInComponentNgFactory:i0.ComponentFactory<i10.A2tSignInComponent> = i0.ɵccf('a2t-sign-in',
    i10.A2tSignInComponent,View_A2tSignInComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWVvdy9hbmd1bGFyMi10b2tlbi9zcmMvYTJ0LXVpL2EydC1zaWduLWluL2EydC1zaWduLWluLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL21lb3cvYW5ndWxhcjItdG9rZW4vc3JjL2EydC11aS9hMnQtc2lnbi1pbi9hMnQtc2lnbi1pbi5jb21wb25lbnQudHMiLCJuZzovLy9ob21lL21lb3cvYW5ndWxhcjItdG9rZW4vc3JjL2EydC11aS9hMnQtc2lnbi1pbi9hMnQtc2lnbi1pbi5jb21wb25lbnQudHMuQTJ0U2lnbkluQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9ob21lL21lb3cvYW5ndWxhcjItdG9rZW4vc3JjL2EydC11aS9hMnQtc2lnbi1pbi9hMnQtc2lnbi1pbi5jb21wb25lbnQudHMuQTJ0U2lnbkluQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgICAgIDxhMnQtaGVhZGxpbmU+U2lnbiBJbjwvYTJ0LWhlYWRsaW5lPlxuICAgICAgICA8YTJ0LWVycm9yIFtlcnJvcnNdPVwiX2Vycm9yc1wiPjwvYTJ0LWVycm9yPlxuICAgICAgICA8YTJ0LWZvcm0+U2lnbiBJbjwvYTJ0LWZvcm0+XG4gICAgICAgIDxhMnQtbGlua3MgY2FzZT1cInNpZ24taW5cIj48L2EydC1saW5rcz5cbiAgICAiLCI8YTJ0LXNpZ24taW4+PC9hMnQtc2lnbi1pbj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLCtDQUNRO01BQUE7TUFBQTthQUFBO1VBQUEsZUFBYyxnQ0FBc0I7VUFBQSxpQkFDcEM7VUFBQTt5Q0FBQSxVQUFBO1VBQUEsbURBQTBDO1VBQUEsaUJBQzFDO1VBQUE7d0NBQUEsVUFBQTtVQUFBLGlEQUFVO01BQWtCLCtDQUM1QjtVQUFBO1VBQUE7YUFBQTtVQUFBLGVBQXNDOztJQUYzQjtJQUFYLFdBQVcsU0FBWDtJQUVXO0lBQVgsWUFBVyxTQUFYOzs7O29CQ0pSO01BQUE7bUNBQUE7d0JBQUEsc0JBQUE7TUFBQTs7OzsifQ==
