/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './a2t-headline.component';
const styles_A2tHeadlineComponent:any[] = ['p[_ngcontent-%COMP%] {\n            text-align: center;\n            color: white;\n            font-size: 30px;\n        }'];
export const RenderType_A2tHeadlineComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:0,
    styles:styles_A2tHeadlineComponent,data:{}});
export function View_A2tHeadlineComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),i0.ɵncd((null as any),
      0)],(null as any),(null as any));
}
export function View_A2tHeadlineComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'a2t-headline',
      ([] as any[]),(null as any),(null as any),(null as any),View_A2tHeadlineComponent_0,
      RenderType_A2tHeadlineComponent)),i0.ɵdid(49152,(null as any),0,i1.A2tHeadlineComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const A2tHeadlineComponentNgFactory:i0.ComponentFactory<i1.A2tHeadlineComponent> = i0.ɵccf('a2t-headline',
    i1.A2tHeadlineComponent,View_A2tHeadlineComponent_Host_0,{},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWVvdy9hbmd1bGFyMi10b2tlbi9zcmMvYTJ0LXVpL2EydC1zaGFyZWQvYTJ0LWhlYWRsaW5lL2EydC1oZWFkbGluZS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9tZW93L2FuZ3VsYXIyLXRva2VuL3NyYy9hMnQtdWkvYTJ0LXNoYXJlZC9hMnQtaGVhZGxpbmUvYTJ0LWhlYWRsaW5lLmNvbXBvbmVudC50cyIsIm5nOi8vL2hvbWUvbWVvdy9hbmd1bGFyMi10b2tlbi9zcmMvYTJ0LXVpL2EydC1zaGFyZWQvYTJ0LWhlYWRsaW5lL2EydC1oZWFkbGluZS5jb21wb25lbnQudHMuQTJ0SGVhZGxpbmVDb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvbWVvdy9hbmd1bGFyMi10b2tlbi9zcmMvYTJ0LXVpL2EydC1zaGFyZWQvYTJ0LWhlYWRsaW5lL2EydC1oZWFkbGluZS5jb21wb25lbnQudHMuQTJ0SGVhZGxpbmVDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8cD48bmctY29udGVudD48L25nLWNvbnRlbnQ+PC9wPiIsIjxhMnQtaGVhZGxpbmU+PC9hMnQtaGVhZGxpbmU+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSwrRUFBRztNQUFBOzs7b0JDQUg7TUFBQTtxQ0FBQSxVQUFBO01BQUE7OzsifQ==
