/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../a2t-shared/a2t-headline/a2t-headline.component.ngfactory';
import * as i2 from '../a2t-shared/a2t-headline/a2t-headline.component';
import * as i3 from '../a2t-shared/a2t-error/a2t-error.component.ngfactory';
import * as i4 from '../a2t-shared/a2t-error/a2t-error.component';
import * as i5 from '../a2t-shared/a2t-form/a2t-form.component.ngfactory';
import * as i6 from '../a2t-shared/a2t-form/a2t-form.component';
import * as i7 from '../a2t-shared/a2t-form/a2t-form.service';
import * as i8 from './a2t-update-password.component';
import * as i9 from '../../angular2-token.service';
import * as i10 from '@angular/router';
const styles_A2tUpdatePasswordComponent:any[] = ([] as any[]);
export const RenderType_A2tUpdatePasswordComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_A2tUpdatePasswordComponent,data:{}});
export function View_A2tUpdatePasswordComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),2,'a2t-headline',([] as any[]),(null as any),(null as any),
      (null as any),i1.View_A2tHeadlineComponent_0,i1.RenderType_A2tHeadlineComponent)),
      i0.ɵdid(49152,(null as any),0,i2.A2tHeadlineComponent,([] as any[]),(null as any),
          (null as any)),(_l()(),i0.ɵted(0,['Update your Password'])),(_l()(),i0.ɵted((null as any),
          ['\n        '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'a2t-error',
          ([] as any[]),(null as any),(null as any),(null as any),i3.View_A2tErrorComponent_0,
          i3.RenderType_A2tErrorComponent)),i0.ɵdid(49152,(null as any),0,i4.A2tErrorComponent,
          ([] as any[]),{errors:[0,'errors']},(null as any)),(_l()(),i0.ɵted((null as any),
          ['\n        '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'a2t-form',
          ([] as any[]),(null as any),(null as any),(null as any),i5.View_A2tFormComponent_0,
          i5.RenderType_A2tFormComponent)),i0.ɵdid(49152,(null as any),0,i6.A2tFormComponent,
          [i7.A2tFormService],(null as any),(null as any)),(_l()(),i0.ɵted(0,['Update Password'])),
      (_l()(),i0.ɵted((null as any),['\n    ']))],(_ck,_v) => {
    var _co:i8.A2tUpdatePasswordComponent = _v.component;
    const currVal_0:any = _co._errors;
    _ck(_v,6,0,currVal_0);
  },(null as any));
}
export function View_A2tUpdatePasswordComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'a2t-update-password',
      ([] as any[]),(null as any),(null as any),(null as any),View_A2tUpdatePasswordComponent_0,
      RenderType_A2tUpdatePasswordComponent)),i0.ɵprd(512,(null as any),i7.A2tFormService,
      i7.A2tFormService,([] as any[])),i0.ɵdid(49152,(null as any),0,i8.A2tUpdatePasswordComponent,
      [i7.A2tFormService,i9.Angular2TokenService,i10.Router],(null as any),(null as any))],
      (null as any),(null as any));
}
export const A2tUpdatePasswordComponentNgFactory:i0.ComponentFactory<i8.A2tUpdatePasswordComponent> = i0.ɵccf('a2t-update-password',
    i8.A2tUpdatePasswordComponent,View_A2tUpdatePasswordComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWVvdy9hbmd1bGFyMi10b2tlbi9zcmMvYTJ0LXVpL2EydC11cGRhdGUtcGFzc3dvcmQvYTJ0LXVwZGF0ZS1wYXNzd29yZC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9tZW93L2FuZ3VsYXIyLXRva2VuL3NyYy9hMnQtdWkvYTJ0LXVwZGF0ZS1wYXNzd29yZC9hMnQtdXBkYXRlLXBhc3N3b3JkLmNvbXBvbmVudC50cyIsIm5nOi8vL2hvbWUvbWVvdy9hbmd1bGFyMi10b2tlbi9zcmMvYTJ0LXVpL2EydC11cGRhdGUtcGFzc3dvcmQvYTJ0LXVwZGF0ZS1wYXNzd29yZC5jb21wb25lbnQudHMuQTJ0VXBkYXRlUGFzc3dvcmRDb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvbWVvdy9hbmd1bGFyMi10b2tlbi9zcmMvYTJ0LXVpL2EydC11cGRhdGUtcGFzc3dvcmQvYTJ0LXVwZGF0ZS1wYXNzd29yZC5jb21wb25lbnQudHMuQTJ0VXBkYXRlUGFzc3dvcmRDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICAgICAgPGEydC1oZWFkbGluZT5VcGRhdGUgeW91ciBQYXNzd29yZDwvYTJ0LWhlYWRsaW5lPlxuICAgICAgICA8YTJ0LWVycm9yIFtlcnJvcnNdPVwiX2Vycm9yc1wiPjwvYTJ0LWVycm9yPlxuICAgICAgICA8YTJ0LWZvcm0+VXBkYXRlIFBhc3N3b3JkPC9hMnQtZm9ybT5cbiAgICAiLCI8YTJ0LXVwZGF0ZS1wYXNzd29yZD48L2EydC11cGRhdGUtcGFzc3dvcmQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsK0NBQ1E7TUFBQTtNQUFBO2FBQUE7VUFBQSxlQUFjLDZDQUFtQztVQUFBLGlCQUNqRDtVQUFBO3lDQUFBLFVBQUE7VUFBQSxtREFBMEM7VUFBQSxpQkFDMUM7VUFBQTt3Q0FBQSxVQUFBO1VBQUEsaURBQVU7TUFBMEI7O0lBRHpCO0lBQVgsV0FBVyxTQUFYOzs7O29CQ0ZSO01BQUE7MkNBQUE7d0JBQUEsc0JBQUE7TUFBQTs7OzsifQ==
